In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [ ]:
data = pd.read_csv('/content/Train.csv')

In [ ]:
data.head()

Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0           FDA15         9.30  ...  Supermarket Type1          3735.1380
1           DRC01         5.92  ...  Supermarket Type2           443.4228
2           FDN15        17.50  ...  Supermarket Type1          2097.2700
3           FDX07        19.20  ...      Grocery Store           732.3800
4           NCD19         8.93  ...  Supermarket Type1           994.7052

[5 rows x 12 columns]

In [ ]:
data.isnull().any()

Item_Identifier              False
Item_Weight                   True
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                   True
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                6113 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


In [ ]:
data['Item_Weight'].fillna(data['Item_Weight'].mean(),inplace=True)

In [ ]:
data['Outlet_Size'].fillna(data['Outlet_Size'].mode()[0],inplace=True)

In [ ]:
data.isnull().any()

Item_Identifier              False
Item_Weight                  False
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                  False
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [ ]:
data.describe()

Item_Weight  ...  Item_Outlet_Sales
count  8523.000000  ...        8523.000000
mean     12.857645  ...        2181.288914
std       4.226124  ...        1706.499616
min       4.555000  ...          33.290000
25%       9.310000  ...         834.247400
50%      12.857645  ...        1794.331000
75%      16.000000  ...        3101.296400
max      21.350000  ...       13086.964800

[8 rows x 5 columns]

In [ ]:
x = data.iloc[:,0:11].values
y = data.iloc[:,11:12].values

In [ ]:
x.shape

(8523, 11)

In [ ]:
y

array([[3735.138 ],
       [ 443.4228],
       [2097.27  ],
       ...,
       [1193.1136],
       [1845.5976],
       [ 765.67  ]])

In [ ]:
data['Item_Outlet_Sales']

0       3735.1380
1        443.4228
2       2097.2700
3        732.3800
4        994.7052
          ...    
8518    2778.3834
8519     549.2850
8520    1193.1136
8521    1845.5976
8522     765.6700
Name: Item_Outlet_Sales, Length: 8523, dtype: float64

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer([("one",OneHotEncoder(),[0,2,4,6,8,9,10])],remainder = "passthrough")
x = ct.fit_transform(x)

In [ ]:
x

<8523x1604 sparse matrix of type '<class 'numpy.float64'>'
	with 93227 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
x_train_sc = sc.fit(x_train)
x_train = x_train_sc.transform(x_train)
x_test = x_train_sc.transform(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = mlr.predict(x_test)

In [ ]:
y_pred

array([[ 2131.6922513 ],
       [ 3271.98644719],
       [ 2393.37699429],
       ...,
       [ 4829.16703352],
       [-1046.18199909],
       [ 5645.50832807]])

In [ ]:
y_test

array([[1426.1436],
       [1201.769 ],
       [1836.2764],
       ...,
       [2885.5772],
       [ 218.3824],
       [5478.2024]])

In [ ]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_pred,y_test)

In [ ]:
accuracy

0.1439691101755578

In [ ]:
#select 

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
 


In [ ]:
from numpy import array 
 
select = SelectKBest(score_func=f_regression, k=5)
z = select.fit_transform(x, y) 
 
z.shape 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(8523, 5)

In [ ]:
z

<8523x5 sparse matrix of type '<class 'numpy.float64'>'
	with 12031 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(z,y,test_size=0.2,random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = mlr.predict(x_test)

In [ ]:
y_pred

array([[2559.09688574],
       [2522.49932259],
       [2094.52569017],
       ...,
       [4166.79931987],
       [-994.00128806],
       [5357.65187947]])

In [ ]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_pred,y_test)

In [ ]:
accuracy

0.20072028707766787